### ISSUE TITLE
Error: angular.element(...).click is not a function

### ISSUE THREAD

**Issue by iamonuwa** [toniton/angular-paystack#2]
I just discovered that on page load, the library displays this error message...

**Comment by iamonuwa** [comment]
I just resolved the problem by changing the 

> angular.element(element).click(function () {});

to 

> angular.element(element).bind('click', function () {});

**Comment by toniton** [comment]
Just checked and everything works fine on my end, try upgrading your version of angular. Everything seems ok here. @iamonuwa

**Comment by stigwue** [comment]
It would have been cool to know which AngularJS versions trigger this error so perhaps we can use bind('click') for v1.0.1 and .click() for perhaps v1.0.2.

I've just had this error triggered by v1.6.3.
