### ISSUE TITLE
Unable to setUp the library to work aright

### ISSUE THREAD

**Issue by AwesomePaul007** [toniton/angular-paystack#7]
Hi guys, working on a project and am using angularjs and nodejs. However, I decided to go with angularjs library for paystack. Am currently using angular 1.65 and I  installed the library and got it up to an extent where the button is rendering on my page, but the below errors are what i see, causing the button not to function well. Is there something am doing wrong ? or has the library been discontinued ?

`Paystack library initialized
angular.js:13708 Error: [ng:areq] http://errors.angularjs.org/1.5.7/ng/areq?p0=PaymentController&p1=not%20a%20function%2C%20got%20undefined
    at http://localhost:4000/sms-engine-interface/core/angular.min.js:6:412
    at sb (http://localhost:4000/sms-engine-interface/core/angular.min.js:22:1013)
    at Qa (http://localhost:4000/sms-engine-interface/core/angular.min.js:23:82)
    at http://localhost:4000/sms-engine-interface/core/angular.min.js:89:782
    at Object.link (http://localhost:4000/sms-engine-interface/core/angular-route.js:1050:26)
    at http://localhost:4000/sms-engine-interface/core/angular.min.js:16:60
    at ja (http://localhost:4000/sms-engine-interface/core/angular.min.js:81:39)
    at m (http://localhost:4000/sms-engine-interface/core/angular.min.js:66:274)
    at g (http://localhost:4000/sms-engine-interface/core/angular.min.js:58:485)
    at http://localhost:4000/sms-engine-interface/core/angular.min.js:58:123 <div class="ng-scope" ng-view="">`

**Comment by toniton** [comment]
Hi @Awesome-Paul, 
Please can you recreate the problem in a fiddle and share. 
That'd be helpful in debugging the error you're facing.

**Comment by AwesomePaul007** [comment]
Thanks @toniton, 

New to fiddle environment though, but i just dropped the controller and the view.. The route is not included and some other files. Just so you can see how i set things up, i'd share screenshot if need be.
https://jsfiddle.net/AwesomePaul/53pzm42r/4/

**Comment by AwesomePaul007** [comment]
> Was able to work around it a bit, the button pops the modal now but with the error " We couldn't start Transaction, enter a valid email address"

![image](https://user-images.githubusercontent.com/23118770/47221809-52fe4a80-d3ad-11e8-92aa-23a4bcdf3182.png)

**Comment by toniton** [comment]
Please refer to [Paystack's documentation](https://developers.paystack.co/docs/) to get this issue resolved as this is not specific to this library.
Hint: I think you are missing a config.
